import type * as monaco from "monaco-editor/esm/vs/editor/editor.api.js";

let goTokenizationRegistered = false;

export function registerGoTokenization(monacoLanguages: typeof monaco.languages) {
  if (goTokenizationRegistered) return;

  monacoLanguages.setMonarchTokensProvider("go", {
    defaultToken: "identifier.variable",
    tokenPostfix: ".go",
    brackets: [
      { open: "{", close: "}", token: "delimiter.curly" },
      { open: "[", close: "]", token: "delimiter.square" },
      { open: "(", close: ")", token: "delimiter.parenthesis" },
    ],
    keywords: [
      "break",
      "case",
      "chan",
      "const",
      "continue",
      "default",
      "defer",
      "else",
      "fallthrough",
      "for",
      "func",
      "go",
      "goto",
      "if",
      "import",
      "interface",
      "map",
      "package",
      "range",
      "return",
      "select",
      "struct",
      "switch",
      "type",
      "var",
    ],
    constants: ["nil", "true", "false", "iota"],
    builtins: [
      "append",
      "cap",
      "clear",
      "close",
      "complex",
      "copy",
      "delete",
      "imag",
      "len",
      "make",
      "max",
      "min",
      "new",
      "panic",
      "print",
      "println",
      "real",
      "recover",
    ],
    builtinTypes: [
      "any",
      "bool",
      "byte",
      "comparable",
      "complex64",
      "complex128",
      "error",
      "float32",
      "float64",
      "int",
      "int8",
      "int16",
      "int32",
      "int64",
      "rune",
      "string",
      "uint",
      "uint8",
      "uint16",
      "uint32",
      "uint64",
      "uintptr",
    ],
    symbols: /[=><!~?:&|+\-*/^%]+/,
    escapes: /\\(?:[abfnrtv\\"']|x[0-9A-Fa-f]{2}|u[0-9A-Fa-f]{4}|U[0-9A-Fa-f]{8}|[0-7]{3})/,
    tokenizer: {
      root: [
        [/\/\/.*$/, "comment"],
        [/\/\*/, "comment", "@comment"],
        [/`/, "string", "@rawString"],
        [/"/, "string", "@string"],
        [/'(?:[^\\']|@escapes)'/, "string"],
        [/\b(func)(\s+)/, ["keyword.function", "white"], "@functionDeclaration"],
        [/(\.)([A-Za-z_]\w*)(?=\s*\()/, ["delimiter.member", "function.call"]],
        [/(\.)([A-Z]\w*)/, ["delimiter.member", "identifier.type"]],
        [/(\.)([A-Za-z_]\w*)/, ["delimiter.member", "identifier.property"]],
        [
          /[A-Za-z_]\w*(?=\s*\()/,
          { cases: { "@builtins": "function.builtin", "@default": "function.call" } },
        ],
        [/[A-Z]\w*/, "identifier.type"],
        [
          /[a-z_]\w*/,
          {
            cases: {
              "@keywords": "keyword",
              "@constants": "constant.language",
              "@builtins": "function.builtin",
              "@builtinTypes": "identifier.type.builtin",
              "@default": "identifier.variable",
            },
          },
        ],
        [/\d*\.\d+([eE][-+]?\d+)?/, "number.float"],
        [/0[xX][0-9a-fA-F_]+/, "number.hex"],
        [/0[bB][01_]+/, "number.binary"],
        [/\d[\d_]*/, "number"],
        [/[{}]/, "delimiter.curly"],
        [/[()]/, "delimiter.parenthesis"],
        [/[[\]]/, "delimiter.square"],
        [/[;,.]/, "delimiter.punctuation"],
        [/@symbols/, "operator"],
        [/\s+/, "white"],
      ],
      functionDeclaration: [
        [/\/\/.*$/, "comment", "@pop"],
        [/\/\*/, "comment", "@comment"],
        [/[A-Za-z_]\w*(?=\s*\()/, "function.declaration", "@pop"],
        [/[A-Z]\w*/, "identifier.type"],
        [
          /[a-z_]\w*/,
          {
            cases: {
              "@builtinTypes": "identifier.type.builtin",
              "@default": "identifier.variable",
            },
          },
        ],
        [/[{}]/, "delimiter.curly"],
        [/[()]/, "delimiter.parenthesis"],
        [/[[\]]/, "delimiter.square"],
        [/[;,.]/, "delimiter.punctuation"],
        [/@symbols/, "operator"],
        [/\s+/, "white"],
      ],
      comment: [
        [/[^/*]+/, "comment"],
        [/\/\*/, "comment", "@push"],
        [/\*\//, "comment", "@pop"],
        [/[/*]/, "comment"],
      ],
      string: [
        [/[^\\"]+/, "string"],
        [/@escapes/, "string.escape"],
        [/\\./, "string.escape.invalid"],
        [/"/, "string", "@pop"],
      ],
      rawString: [
        [/[^`]+/, "string"],
        [/`/, "string", "@pop"],
      ],
    },
  });

  goTokenizationRegistered = true;
}
